name: WorldEvents
version: '${version}'
main: org.nevermined.worldevents.WorldEvents
api-version: '1.16'
softdepend: [ PlaceholderAPI ]
author: Wyne
description: Manages gameplay events
website: https://github.com/NeverMined-Entertainment/WorldEvents
permissions:
  wevents.queuecontrol:
    description: 'Allows to start/stop event queues'
